export default Object.freeze({
  BLOOD_PRESSURE_RESULTS: "BPResults",
  ECG_RESULTS: "ECGResults",
  PAEDS_HOMEPAGE: "PaedsHomepage",
  BLOOD_PRESSURE: "BloodPressure",
  BODY_SURFACE_AREA: "BSA",
  PAEDIATRIC_CENTILE: "PCentile",
  PAEDIATRIC_CENTILE_RESULTS: "PCentileResultsScreen",
  ECG: "ECG",
  FLUID_CALCULATOR: "FluidCalculator",
  WETFLAG: "WETFLAG",
  NEONATE_HOMEPAGE: "NeonateHomepage",
  BIRTH_CENTILE: "BirthCentile",
  BIRTH_CENTILE_RESULTS: "BirthCentileResults",
  NEONATE_CENTILE: "NCentile",
  NEONATE_CENTILE_RESULTS: "NCentileResults",
  ENDOTRACHEAL_TUBE_LENGTH: "EndotrachealTube",
  ENTERAL_FEED: "EnteralFeed",
  JAUNDICE: "Jaundice",
  APLS_LOG: "APLSLog",
  APLS: "APLSScreen",
});
